### ISSUE TITLE
Service.update updating strategy

### ISSUE THREAD

**Issue by typedef42** [atomictech/aurelia-collection#2]
For now the update() method wait for backend response, and set the responded json to the model attributes.

It causes problem when backend response is not what the model expects.
For example Dates : 
On the get from service the constructor method of a model can transform a date sent as string by the backend response.
But on the service update case, the model has no chance to transform the response from the backend and then have its date attributes overwriten by strings.

Maybe we should merge the local json (body argument of the update) instead of the response of the backend.

**Comment by typedef42** [comment]
I think you are right, let's implement a better callback strategy that allow unserialising of backend response.

**Comment by chabou-san** [comment]
I think that is the real good answer, yes.
